---

-hosts: all
  tasks:
  -name: install neovim
    package:
      name: neovim


- hosts: db_servers
  tasks:
  - name: install mysql
    package: 
      name: 
        - mysql

- hosts: analysis_server
  tasks:
  - name: install python and node
    package:
      name:
      - "{{ python_package }}"
      - nodejs
  - name: copy test file
    copy:
      src: test_file.txt
      dest: ~/test_file.txt
