---

- hosts: db_servers
  tasks:
  - name: install mysql
    package: 
      name: 
        - mysql_server

- hosts: analysis_server
  tasks:
  - name: install python and node
    package:
      name:
      - "{{ python_package }}"
      - nodejs
